# Generated by Django 3.2.2 on 2021-11-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='operate_from',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
