# Generated by Django 3.2.2 on 2021-12-01 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
        ('account', '0005_alter_user_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agency',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='agency.agency'),
        ),
    ]
