# Generated by Django 3.2.2 on 2021-12-02 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
        ('account', '0006_user_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agency',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='agency.agency'),
        ),
    ]
