# Generated by Django 3.2.2 on 2021-11-23 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(choices=[('0', 'Central'), ('1', 'City'), ('2', 'District'), ('3', 'Commune'), ('4', 'Village')], default='1', max_length=30)),
                ('completed_declare', models.BooleanField(default=False)),
                ('sup_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_agencies', to='agency.agency')),
            ],
        ),
    ]
