# Generated by Django 3.2.2 on 2021-11-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.CharField(db_index=True, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('dob', models.DateTimeField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=30)),
                ('ethnic', models.CharField(blank=True, max_length=30)),
                ('injected_vaccines', models.IntegerField(default=0)),
            ],
        ),
    ]
