# Generated by Django 3.2.2 on 2021-11-26 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_alter_citizen_dob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Citizen',
        ),
    ]
