# Generated by Django 3.2.2 on 2021-11-26 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('citizen', '0003_delete_citizen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=30)),
                ('ethnic', models.CharField(blank=True, max_length=30)),
                ('injected_vaccines', models.IntegerField(default=0)),
                ('declarer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declared_ctizens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
