# Generated by Django 3.2.2 on 2021-12-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0005_auto_20211201_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='educational',
            field=models.CharField(choices=[('none', 'None'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('high', 'High'), ('university', 'University'), ('Master', 'Master')], default='high', max_length=30),
        ),
    ]
