# Generated by Django 3.2.2 on 2021-12-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0006_alter_citizen_educational'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='create',
            field=models.DateField(),
        ),
    ]
