# Generated by Django 3.2.2 on 2021-12-01 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
        ('citizen', '0008_citizen_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citizens', to='agency.agency'),
        ),
    ]
