# Generated by Django 3.2.2 on 2021-12-01 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0010_citizen_dod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='create',
            new_name='created',
        ),
    ]
