# Generated by Django 3.2.2 on 2021-12-01 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0011_rename_create_family_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='citizen.family'),
        ),
    ]
