# Generated by Django 3.2.2 on 2021-12-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0014_auto_20211206_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='family',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
    ]
