# Generated by Django 3.2.2 on 2021-12-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0015_auto_20211206_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='dod',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='marital_status',
        ),
    ]
